# Generated by Django 2.2.14 on 2021-04-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(max_length=128, verbose_name='标题')),
                ('website', models.URLField(max_length=128, null=True, verbose_name='网页链接')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('label_tag', models.CharField(choices=[('section', '专栏'), ('thinking', '想法')], default='thinking', max_length=20, verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(default='New_Game', max_length=20, verbose_name='比赛名称')),
                ('match_season', models.CharField(max_length=20, null=True, verbose_name='赛季')),
                ('match_time', models.CharField(max_length=20, null=True, verbose_name='比赛时间')),
                ('match_location', models.CharField(max_length=20, null=True, verbose_name='比赛地点')),
                ('match_object', models.CharField(max_length=20, null=True, verbose_name='面向对象')),
                ('group_num', models.PositiveIntegerField(choices=[(1, '无小组'), (2, 'AB组'), (3, 'ABC组'), (4, 'ABCD组')], default=1, verbose_name='小组数')),
                ('team_num', models.PositiveIntegerField(default=2, verbose_name='球队数')),
                ('match_rule', models.CharField(choices=[('group_dieout', '小组淘汰赛'), ('circle', '大循环'), ('onechance_dieout', '单轮淘汰')], default='group_dieout', max_length=20, verbose_name='赛制')),
                ('match_picture', models.ImageField(default='image/default.png', upload_to='image/', verbose_name='比赛简照')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20, verbose_name='球队名称')),
                ('team_num', models.CharField(choices=[('1', '一班'), ('2', '二班'), ('3', '三班'), ('4', '四班'), ('5', '五班'), ('6', '六班'), ('7', '七班'), ('8', '八班'), ('9', '九班'), ('10', '十班'), ('11', '十一班'), ('12', '十二班'), ('13', '十三班'), ('14', '十四班'), ('15', '十五班'), ('16', '十六班'), ('-1', '其他')], default='-1', max_length=10, verbose_name='班号')),
                ('team_introduction', models.CharField(max_length=100, null=True, verbose_name='球队简介')),
                ('team_group', models.CharField(choices=[('groupA', 'A组'), ('groupB', 'B组'), ('groupC', 'C组'), ('groupD', 'D组'), ('undefined', '未定义')], default='undefined', max_length=10, verbose_name='所属小组')),
                ('isOut', models.CharField(choices=[('ready', '准备中'), ('group', '小组赛'), ('dieout', '淘汰赛'), ('out', '已结束')], default='ready', max_length=10, verbose_name='所属阶段')),
                ('team_picture', models.ImageField(default='image/laker.jpg', upload_to='image/', verbose_name='队标')),
                ('matcht', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bfb.Match', verbose_name='对应比赛')),
            ],
            options={
                'verbose_name': '球队信息',
                'verbose_name_plural': '球队信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('undefined', '说不好')], default='undefined', max_length=24, verbose_name='性别')),
                ('cre_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.CharField(default=None, max_length=24, null=True, verbose_name='上次登陆时间')),
                ('is_superuser', models.IntegerField(choices=[(0, '普通用户'), (1, '超级用户')], default=0, verbose_name='是否超级用户')),
                ('has_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '社区用户',
                'verbose_name_plural': '社区用户',
                'ordering': ['-cre_time'],
            },
        ),
        migrations.CreateModel(
            name='TeamVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.CharField(max_length=256, verbose_name='留言板')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bfb.User', verbose_name='留言者')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfb.Team', verbose_name='对应球队')),
            ],
            options={
                'verbose_name': '球队留言板',
                'verbose_name_plural': '球队留言板',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('netscore', models.IntegerField(default=0, verbose_name='净胜分')),
                ('rank', models.IntegerField(default=0, verbose_name='排名')),
                ('num_win', models.IntegerField(default=0, verbose_name='胜场数')),
                ('num_lose', models.IntegerField(default=0, verbose_name='负场数')),
                ('belong_team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bfb.Team', verbose_name='球队')),
            ],
            options={
                'verbose_name': '得分情况',
                'verbose_name_plural': '得分情况',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_1st', models.CharField(default='无', max_length=20, null=True, verbose_name='冠军')),
                ('result_2nd', models.CharField(default='无', max_length=20, null=True, verbose_name='亚军')),
                ('result_3rd', models.CharField(default='无', max_length=20, null=True, verbose_name='季军')),
                ('result_4th', models.CharField(default='无', max_length=20, null=True, verbose_name='殿军')),
                ('result_mvp', models.CharField(default='无', max_length=20, null=True, verbose_name='最有价值球员')),
                ('matchr', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bfb.Match', verbose_name='对应赛事')),
            ],
            options={
                'verbose_name': '比赛结果',
                'verbose_name_plural': '比赛结果',
            },
        ),
        migrations.CreateModel(
            name='Match_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_stage', models.CharField(choices=[('unstarted', '未开始'), ('inprogress', '进行中'), ('ended', '已结束')], default='unstarted', max_length=10, verbose_name='比赛阶段')),
                ('match_progress', models.CharField(choices=[('group', '小组赛'), ('dieout', '淘汰赛'), ('end', '结束')], default='group', max_length=10, verbose_name='比赛进展')),
                ('dieout_progress', models.IntegerField(choices=[(1, '阶段1'), (2, '阶段2'), (3, '阶段3'), (4, '阶段4'), (-1, '非淘汰赛')], default=-1, verbose_name='淘汰赛阶段')),
                ('isPause', models.BooleanField(default=True, verbose_name='是否暂停')),
                ('match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bfb.Match', verbose_name='对应赛事')),
            ],
            options={
                'verbose_name': '比赛状态',
                'verbose_name_plural': '比赛状态',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_style', models.CharField(choices=[('group', '小组赛'), ('dieout', '淘汰赛')], default='group', max_length=20, verbose_name='竞赛类型')),
                ('contest_state', models.CharField(choices=[('unstarted', '未开始'), ('ready', '准备中'), ('ended', '已结束')], default='unstarted', max_length=20, verbose_name='竞赛状态')),
                ('dieout_progress', models.IntegerField(choices=[(1, '阶段1'), (2, '阶段2'), (3, '阶段3'), (4, '阶段4'), (-1, '非淘汰赛')], default=-1, verbose_name='淘汰赛阶段')),
                ('cs1', models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='1队得分')),
                ('cs2', models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='2队得分')),
                ('contest_date', models.CharField(default='01-01', max_length=50, null=True, verbose_name='对阵日期')),
                ('contest_time', models.CharField(default='00:00', max_length=50, null=True, verbose_name='对阵时间')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('contest_content', models.CharField(blank=True, max_length=500, null=True, verbose_name='对阵详情')),
                ('battle_teams', models.ManyToManyField(related_name='contest', to='bfb.Team', verbose_name='对应球队')),
                ('matchc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bfb.Match', verbose_name='对应赛事')),
            ],
            options={
                'verbose_name': '竞赛内容',
                'verbose_name_plural': '竞赛内容',
                'ordering': ['-pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('picture', models.ImageField(null=True, upload_to='image/', verbose_name='配图')),
                ('num_liked', models.PositiveSmallIntegerField(default=0, verbose_name='点赞数')),
                ('num_comment', models.PositiveSmallIntegerField(default=0, verbose_name='评论数')),
                ('num_visited', models.PositiveSmallIntegerField(default=0, verbose_name='浏览次数')),
                ('art', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bfb.Article')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
            },
        ),
        migrations.CreateModel(
            name='ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bfb.User')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bfb.Article')),
                ('discusser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bfb.User')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ath_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('ath_picture', models.ImageField(default='image/head_default.png', upload_to='image/', verbose_name='头像')),
                ('ath_sno', models.CharField(max_length=20, null=True, verbose_name='学号')),
                ('ath_bir', models.CharField(max_length=20, null=True, verbose_name='出生年月')),
                ('ath_height', models.FloatField(default=0, null=True, verbose_name='身高')),
                ('ath_weight', models.FloatField(default=0, null=True, verbose_name='体重')),
                ('ath_position', models.CharField(choices=[('pg', '组织后卫'), ('sg', '得分后卫'), ('sf', '小前锋'), ('pf', '大前锋'), ('c', '中锋'), ('undefined', '未定义')], default='undefined', max_length=20, verbose_name='司职')),
                ('ath_number', models.IntegerField(default=-1, verbose_name='号码')),
                ('isCaptain', models.BooleanField(default=False, verbose_name='队长')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bfb.Team', verbose_name='所属球队')),
            ],
            options={
                'verbose_name': '运动员信息',
                'verbose_name_plural': '运动员信息',
            },
        ),
        migrations.CreateModel(
            name='ArticleUpDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField(default=False, verbose_name='点赞？')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfb.Article', verbose_name='文章')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bfb.User')),
            ],
            options={
                'verbose_name': '点赞详情',
                'verbose_name_plural': '点赞详情',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bfb.User'),
        ),
    ]
